/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeManagement;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TIAN XIAOWEI
 */
public class JohoToroku extends javax.swing.JFrame {

    /**
     * Creates new form JohoToroku
     */
    public JohoToroku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sex = new javax.swing.ButtonGroup();
        del_flag = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        birthday = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        sexm = new javax.swing.JRadioButton();
        sexf = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hire_date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        post_code = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        final_education = new javax.swing.JComboBox<>();
        graduation_school = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        contract = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        japanese = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        working_time = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        zairyukikan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("社員番号：");

        jLabel2.setText("名前：");

        jLabel3.setText("性別：");

        jLabel4.setText("誕生日：");

        jLabel5.setText("電話番号：");

        sex.add(sexm);
        sexm.setText("男（M）");
        sexm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexmActionPerformed(evt);
            }
        });

        sex.add(sexf);
        sexf.setText("女（F）");
        sexf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexfActionPerformed(evt);
            }
        });

        jLabel6.setText("メール：");

        jLabel7.setText("入社日：");

        jLabel8.setText("郵便番号：");

        jLabel9.setText("住所：");

        jLabel10.setText("最終学歴：");

        jLabel12.setText("卒業学校：");

        final_education.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "専門学校", "大学", "大学院", "短期大学", "なし" }));
        final_education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final_educationActionPerformed(evt);
            }
        });

        jLabel13.setText("契約：");

        contract.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "契約社員", "正社員" }));

        jLabel14.setText("日本語能力：");

        jLabel15.setText("一日労働時間：");

        jLabel16.setText("在留期間：");

        jButton1.setText("登録");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("編集");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("戻る");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("情報一覧");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(graduation_school))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(tel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(birthday)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sexm)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sexf))
                                .addComponent(id)
                                .addComponent(name)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(post_code)
                                .addComponent(email)
                                .addComponent(hire_date)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(address))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(final_education, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel11))
                    .addComponent(jLabel17))
                .addGap(170, 170, 170)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(contract, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(japanese)
                            .addComponent(working_time)
                            .addComponent(zairyukikan)))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(contract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(japanese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(sexf)
                        .addComponent(jLabel15)
                        .addComponent(working_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zairyukikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(hire_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(post_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(final_education, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(graduation_school, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        //登録
        
        
        Connection conn = null;
        Statement stmt = null;
        ResultSet rset = null;

        final String url = "jdbc:postgresql://localhost:5432/tian";
        final String user = "postgres";
        final String password = "Dd345678";
        
        

        try {
            conn = DriverManager.getConnection(url, user, password);
            stmt =  conn.createStatement();
           
            
                    
            String s = null;

            if(sexm.isSelected()){
                s = "男";
            }else{
                s = "女";
            }
            

            //select文実行するには　executeQueryメゾット！！！
          String sql = "INSERT "
                    + "INTO shain_joho( "
                    + "    id "
                    + "    , name "
                    + "    , sex "
                    + "    , birthday "
                    + "    , tel"
                    + "    , email"
                    + "    , post_code"
                    + "    , address"
                    + "    ,final_education"
                    + "    ,graduation_school"
                    + "    ,contract"
                    + "    ,japanese"
                    + "    ,working_time"
                    + "    ,zairyukikan"
                    + "    ,hire_date"
                    + "    ,del_flag"
                    + ") "
                    + "VALUES ( "
                    + "'" + id.getText() + "'" + ","
                    + "'" + name.getText() + "'" + ","
                    + "'" + s + "'" + ","
                    + "'" + birthday.getText() + "'" + ","
                    + "'" + tel.getText() + "'" + ","
                    + "'" + email.getText() + "'" + ","
                    + "'" + post_code.getText() + "'" + ","
                    + "'" + address.getText() + "'" + ","
                    + "'" + final_education.getSelectedItem()+ "'" + ","
                    + "'" + graduation_school.getText() + "'" + ","
                    + "'" + contract.getSelectedItem()+ "'" + ","
                    + "'" + japanese.getText() + "'" + ","
                    + "'" + working_time.getText() + "'" + ","
                    + "'" + zairyukikan.getText() + "'" + ","
                    + "'" + hire_date.getText() + "'" + ","
                    + "'" + 0 + "'" + ")" + ";";
          
          
             System.out.print(sql);
            
            stmt.executeUpdate(sql);
         
            stmt.close();
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(JohoToroku.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //編集
        
        //接続.

        Connection conn = null;

        //sql操作

        Statement stmt = null;

        ResultSet rset = null;



        final String url = "jdbc:postgresql://localhost:5432/tian";

        final String user = "postgres";

        final String password = "Dd345678";



        try {

            conn = DriverManager.getConnection(url, user, password);

            stmt = conn.createStatement();
            
            
            String s = null;

            if(sexm.isSelected()){
                s = "男";
            }else{
                s = "女";
            }



            //select文実行するには　executeQueryメゾット！！！

            String sql = "UPDATE shain_joho "

                    + "set name =" + "'" +  name.getText() + "'" + ","
                    + "birthday=" + "'" + birthday.getText() + "'" + ","
                    + "sex=" + "'" + s + "'" + ","
                    + " tel =" + "'" + tel.getText() + "'" + ","
                    + " email =" + "'" + email.getText() + "'" + ","
                    + " post_code =" + "'" + post_code.getText() + "'" + ","
                    + " address =" + "'" + address.getText() + "'" + ","
                    + " final_education =" + "'" + final_education.getSelectedItem() + "'" + ","
                    + " graduation_school =" + "'" + graduation_school.getText() + "'" + ","
                    + " contract =" + "'" + contract.getSelectedItem() + "'" + ","
                    + " japanese =" + "'" + japanese.getText() + "'" + ","
                    + "working_time =" + "'" + working_time.getText() + "'" + ","
                    + " zairyukikan =" + "'" + zairyukikan.getText() + "'" + ","
                    + " hire_date =" + "'" + hire_date.getText() + "'" + ","
                    + "where id =" + "'" + id.getText()+ "'" + ";";

            //更新

            System.out.print(sql);
            
            stmt.executeUpdate(sql);
            
            



            stmt.close();

            conn.close();

        } catch (SQLException ex) {



            Logger.getLogger(JohoToroku.class.getName()).log(Level.SEVERE, null, ex);



        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void final_educationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final_educationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_final_educationActionPerformed

    private void sexmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexmActionPerformed

    private void sexfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexfActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        //情報一覧画面に行く
        Johoitiran ji = new Johoitiran();
        ji.setVisible(true);
       
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        //メニューに戻る
        Menu me = new Menu();
        me.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel df = (DefaultTableModel) Johoitiran.jTable1.getModel();
        int row = Johoitiran.jTable1.getSelectedRow();
        
        
        
        id.setText(df.getValueAt(row, 0).toString());
        name.setText(df.getValueAt(row, 1).toString());
        birthday.setText(df.getValueAt(row, 3).toString());
        tel.setText(df.getValueAt(row, 4).toString());
        email.setText(df.getValueAt(row, 5).toString());
        post_code.setText(df.getValueAt(row, 6).toString());
        address.setText(df.getValueAt(row, 7).toString());
        final_education.getSelectedItem();
        graduation_school.setText(df.getValueAt(row, 9).toString());
        contract.getSelectedItem();
        japanese .setText(df.getValueAt(row, 11).toString());
        working_time.setText(df.getValueAt(row, 12).toString());
        zairyukikan.setText(df.getValueAt(row, 13).toString());
        hire_date.setText(df.getValueAt(row, 14).toString());
        
        
        
        
        
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JohoToroku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JohoToroku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JohoToroku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JohoToroku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JohoToroku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField birthday;
    private javax.swing.JComboBox<String> contract;
    private javax.swing.ButtonGroup del_flag;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> final_education;
    private javax.swing.JTextField graduation_school;
    private javax.swing.JTextField hire_date;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField japanese;
    private javax.swing.JTextField name;
    private javax.swing.JTextField post_code;
    private javax.swing.ButtonGroup sex;
    private javax.swing.JRadioButton sexf;
    private javax.swing.JRadioButton sexm;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField working_time;
    private javax.swing.JTextField zairyukikan;
    // End of variables declaration//GEN-END:variables
}
